language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: 5Y3Si2JFXkXfHBbugeaWhU4DfYBLM/ZNilzxQUWAhr71tZgFt+C4RQlNrs3sDi5qT6kDVNnb5EmVzIm/HR+vOzo6TZ9jnrPlWwC6zXzsWjUvcY6qTOcJNit6Ayibm1ksdTDl8Hxsel1hpEj4SDc65l+VEYAtTyn4vaa9qIs025ZaNmZYtPDaCo2HNO0oJqY75Zb7zvuN+ndszDOlACZtvZZ8Jj6FHoJ2qAenKKmiQhtEF1uPxFPtiPumxoE3lKB0Ned5aO3yU5hhNk8Icf9VhPaYXhtfWkUx0fT6y18ZMMyFHNQXZ577wBd8OZhGOCnrA12LSF+DsUtRTU6JG72fmtiIUWQrslSpBRFYqhAe01dwhv55SS+h89xuRUUVFdWYfxAmaLqPrWvfNX0jXzVzTGKjE6reCR3nLh//gRwIdBldPYfLK6SrMdu+ssB4xuXzEV0m6ngjodBNX4+rV0DNPTcy/c97x1p0iyDfoUkU6WOclmA81pz8mBnwvE4b5iyhN9JScydKGJuwDd+SGO7h+lIdmeRWHThFRTVtfWUujK4QNGnQiLWpsJbAuuHfrQPukoOtsUA13GiSCnJQzJGhmOOjnKBReibBoUBhqIPaFPD1cEHhFyma+nHFDI5bl+4H1vjE/B4kXQm5UQRjtRN4M9iw71jBxrL0pKA/VQzRMdw=
  app: agendatechrmc
